apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    isDefault: true
    url: http://prometheus:9090
