name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes: { label: Problem statement, placeholder: It would be great if… }
  - type: textarea
    id: proposal
    attributes: { label: Proposed solution }
