name: CI
on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compose-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate docker-compose.yml (with CI override)
        run: docker compose -f docker-compose.yml -f .ci/compose-fix.yml config -q
