name: CI
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
  pull_request:

jobs:
  compose-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate docker-compose.yml
        run: docker compose -f docker-compose.yml config -q

  compose-build:
    runs-on: ubuntu-latest
    needs: compose-validate
    steps:
      - uses: actions/checkout@v4
      - name: Build all services
        run: docker compose -f docker-compose.yml build
