name: CI
on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compose-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug
        run: |
          docker version
          docker compose version
          printf "--- docker-compose.yml ---\n"
          sed -n \"1,200p\" docker-compose.yml
          echo \"--- compose config ---\"
      - name: Validate docker-compose.yml
        run: docker compose -f docker-compose.yml config
      - name: Validate docker-compose.yml
        run: docker compose -f docker-compose.yml config -q
